version: '2'

# Registration of named volumes
volumes:
  asterisk:
  owfs:
  openhab:

services:
  config:
    build: ./config
    volumes:
    - 'asterisk:/data/asterisk:rw'
    - 'owfs:/data/owfs:rw'
    - 'openhab:/data/openhab:rw'

  asterisk:
    build: ./asterisk
    depends_on:
    - config
    network_mode: host
    tty: true
    volumes:
    - 'asterisk:/data/asterisk:ro'

  owfs:
    build: ./owfs
    depends_on:
    - config
    network_mode: host
    expose:
    - "4304"
    volumes:
    - 'owfs:/data/owfs:ro'

  openhab2:
    build: openhab
    image: openhab/openhab:2.3.0-amd64-debian
    depends_on:
    - config
    network_mode: host
    tty: true
    expose:
    - "8080"
    volumes:
    - 'openhab:/data/openhab:ro'
