version: '2'

# Registration of named volumes
volumes:
  asterisk-conf:
  asterisk-sounds:
  owfs-conf:
  openhab-conf:
  openhab-userdata:
  openhab-addons:

services:
  asterisk:
    build: ./asterisk
    network_mode: host
    tty: true
    volumes:
      - 'asterisk-conf:/etc/asterisk:ro'
      - 'asterisk-sounds:/var/lib/asterisk/sounds:ro'

  owfs:
    build: ./owfs
    network_mode: host
    expose:
      - "4304"
    volumes:
      - 'owfs-conf:/etc/owfs.conf:ro'

  openhab2:
    image: openhab/openhab:2.3.0-amd64-debian
    network_mode: host
    tty: true
    expose:
      - "8080"
    volumes:
      - 'openhab-conf:/openhab/conf:ro'
      - 'openhab-userdata:/openhab/userdata:rw'
      - 'openhab-addons:/openhab/addons:ro'
