version: '2'

# Registration of named volumes
volumes:
  asterisk:
  mosquitto:
  owfs:
  pihole:
  signal:
  openhab:

services:
  config:
    build: ./config
    volumes:
    - 'asterisk:/data/asterisk:rw'
    - 'owfs:/data/owfs:rw'
    - 'openhab:/data/openhab:rw'
    - 'mosquitto:/data/mosquitto:rw'
    - 'signal:/data/signal:rw'
    - 'pihole:/data/pihole:rw'

  asterisk:
    build: ./asterisk
    depends_on:
    - config
    network_mode: host
    volumes:
    - 'asterisk:/data/asterisk:ro'

  mosquitto:
    build: ./mosquitto
    depends_on:
    - config
    network_mode: host
    volumes:
    - 'mosquitto:/data/mosquitto:ro'

  owfs:
    build: ./owfs
    depends_on:
    - config
    network_mode: host
    expose:
    - "4304"
    volumes:
    - 'owfs:/data/owfs:ro'

  pihole:
    build: ./pihole
    depends_on:
    - config
    cap_add:
    - NET_ADMIN
    network_mode: host
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
    - "80:80"
    - "443:443"
    dns:
    - 127.0.0.1
    - 1.1.1.1
    volumes:
    - 'pihole:/data/pihole:rw'

  signal:
    image: agileek/signal-cli:latest
    depends_on:
    - config
    volumes:
    - 'signal:/config:rw'

  openhab2:
    build: ./openhab
    depends_on:
    - config
    network_mode: host
    tty: true
    expose:
    - "8080"
    volumes:
    - 'openhab:/data/openhab:rw'
