version: '2'

# Registration of named volumes
volumes:
  asterisk:
  mosquitto:
  owfs:
  pihole-config:
  pihole-dnsmasq-config:
  signal:
  openhab-addons:
  openhab-conf:
  openhab-userdata:
  status:
  unbound:

services:
  config:
    build: ./config
    volumes:
    - 'asterisk:/data/asterisk:rw'
    - 'owfs:/data/owfs:rw'
    - 'openhab-addons:/data/openhab-addons:rw'
    - 'openhab-conf:/data/openhab-conf:rw'
    - 'mosquitto:/data/mosquitto:rw'
    - 'pihole-config:/data/pihole-config:rw'
    - 'pihole-dnsmasq-config:/data/pihole-dnsmasq-config:rw'
    - 'status:/data/status:rw'
    - 'signal:/data/signal:rw'
    - 'unbound:/data/unbound:rw'

  asterisk:
    build: ./asterisk
#    depends_on:
#    - config
    network_mode: host
    volumes:
    - 'asterisk:/data/asterisk:ro'

  mosquitto:
    build: ./mosquitto
#    depends_on:
#    - config
    ports:
    - "1883:1883"
    network_mode: host
    volumes:
    - 'mosquitto:/data/mosquitto:ro'

  owfs:
    build: ./owfs
#    depends_on:
#    - config
#    devices:
#    - "/dev/bus/usb/004/003:/dev/bus/usb/004/003"
#    - "/dev/bus/usb/004/004:/dev/bus/usb/004/004"
#    - "/dev/bus/usb/004/005:/dev/bus/usb/004/005"
    network_mode: host
    ports:
    - "2121:2121"
    volumes:
    - 'owfs:/etc/owfs:ro'

  pihole:
    build: ./pihole
    privileged: true
    volumes:
    - 'pihole-config:/etc/pihole'
    - 'pihole-dnsmasq-config:/etc/dnsmasq.d'
    cap_add:
    - 'NET_ADMIN'
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
    - "80:80/tcp"
    - "443:443/tcp"
    dns:
    - '127.0.0.1'
    - '1.1.1.1'
    network_mode: host

  unbound:
    build: ./unbound
    volumes:
    - 'unbound:/opt/unbound/etc/unbound'
    ports:
    - '1053:53/tcp'
    - '1053:53/udp'

#  signal:
#    image: agileek/signal-cli:latest
#    depends_on:
#    - config
#    volumes:
#    - 'signal:/config:rw'

  openhab2:
    build: ./openhab
#    depends_on:
#    - config
    network_mode: host
    tty: true
    ports:
    - "8080:8080"
    - "8443:8443"
    volumes:
    - 'openhab-addons:/openhab/addons:rw'
    - 'openhab-conf:/openhab/conf:rw'
    - 'openhab-userdata:/openhab/userdata:rw'

#  status:
#    image: yeasy/simple-web:latest
#    ports:
#    - "3000:80"
#    volumes:
#    - 'status:/app/public:rw'
