version: '2'

# Registration of named volumes
volumes:
  asterisk:
  mosquitto:
  owfs:
  signal:
  openhab:

services:
  config:
    build: ./config
    volumes:
    - 'asterisk:/data/asterisk:rw'
    - 'owfs:/data/owfs:rw'
    - 'openhab:/data/openhab:rw'

  asterisk:
    build: ./asterisk
    depends_on:
    - config
    network_mode: host
    volumes:
    - 'asterisk:/data/asterisk:ro'

  mosquitto:
    build: ./mosquitto
    depends_on:
    - config
    network_mode: host
    volumes:
    - 'mosquitto:/data/mosquitto:ro'

  owfs:
    build: ./owfs
    depends_on:
    - config
    network_mode: host
    expose:
    - "4304"
    volumes:
    - 'owfs:/data/owfs:ro'

  pihole:
    build: ./pihole
    depends_on:
    - config
    network_mode: host
#    volumes:
#    - 'asterisk:/data/asterisk:ro'

  signal:
    image: agileek/signal-cli:latest
    depends_on:
    - config
    volumes:
    - 'signal:/config:ro'

  openhab2:
    build: ./openhab
    depends_on:
    - config
    network_mode: host
    tty: true
    expose:
    - "8080"
    volumes:
    - 'openhab:/data/openhab:rw'
