FROM balenalib/amd64-debian:jessie

RUN apt-get update && apt-get install -y \
	ow-shell \
  owhttpd \
	owserver  && \
	rm -rf /var/lib/apt/lists/*

COPY owfs.conf /etc/owfs.conf
COPY app.sh /app.sh
RUN chmod +x /app.sh

EXPOSE 4304
CMD ["/app.sh"]
